### PR TITLE
Make title-casing optional

### PR DESCRIPTION
**Pull request by Goorzhel**
```python
#!/usr/bin/env python

import beancount_chase

CONFIG = [
    beancount_chase.CreditImporter(
        "Liabilities:Chase", currency="USD", lastfour="....", title_case=False
    ),
]
```
```
❯ bean-extract config.py -f main.beancount download | grep SWENSENS -A2
2023-12-01 * "SWENSENS"
  Liabilities:Chase  -16.00 USD

```

### CODE REVIEW

**Review by mtlynch — CHANGES_REQUESTED** [review]
Thanks for adding this!

The changes look good, but would it be possible to add test cases to `checking_test.py` and `credit_test.py` to exercise the new behavior?

**Comment by Goorzhel** [comment]
D'oh. New commit shortly.

**Comment by Goorzhel** [comment]
```
❯ pytest -r p | grep title_c
PASSED beancount_chase/checking_test.py::test_doesnt_title_case_if_asked_not_to
PASSED beancount_chase/credit_test.py::test_doesnt_title_case_if_asked_not_to
```

**Comment by mtlynch** [comment]
@Goorzhel - Sorry, I was trying to push a formatting change ([53a8c92](https://github.com/mtlynch/beancount-chase-bank/pull/112/commits/53a8c921ffc1ee4c4b57c4c930b9b5ef5699e716)) to this branch and accidentally pushed my `master` branch to yours. I re-did the PR in #112 and merged it in. I'll cut a release now.

**Comment by Goorzhel** [comment]
No problem at all. Thanks!

**Pull request closed without merging**
